language: node_js
node_js:
- '7'
- '6'
- '4.3'
script:
- npm run lint
- npm test
after_success:
- npm run coveralls
- npm run bench
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: Nordstrom/ctrace-js
